name: Build

on:
  push:
    branches:
      - '*.x'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  release:
    types: [created]
  workflow_dispatch: ~

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
        os: [ubuntu-latest]
        composer-mode: [update]
        symfony-version: ['']
        include:
          # Build on the lowest supported PHP with the lowest supported dependencies
          - php: 8.2
            os: ubuntu-latest
            composer-mode: lowest
            symfony-version: ''

          # MacOS on latest PHP only
          - php: 8.5
            os: macos-latest
            composer-mode: update
            symfony-version: ''

          # Windows on latest PHP only
          - php: 8.5
            os: windows-latest
            composer-mode: update
            symfony-version: ''

          # Symfony LTS jobs:
          - php: 8.2
            os: ubuntu-latest
            composer-mode: update
            symfony-version: '5.4'

          - php: 8.2
            os: ubuntu-latest
            composer-mode: update
            symfony-version: '6.4'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          ini-file: "development"
          ini-values: "phar.readonly=0,zend.exception_ignore_args=Off"
          coverage: none

      - name: Install symfony/flex
        if: matrix.symfony-version != ''
        run: |
          composer config --global --no-plugins allow-plugins.symfony/flex true &&
          composer global require symfony/flex

      - name: Install latest dependencies
        if: matrix.composer-mode == 'update'
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}.*
        run: composer update

      - name: Install lowest dependencies
        if: matrix.composer-mode == 'lowest'
        run: composer update --prefer-lowest

      - name: Run tests (phpunit)
        run: ./vendor/bin/phpunit

      - name: Run tests (Behat)
        run: ./bin/behat -fprogress --strict

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.5]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          ini-values: "zend.exception_ignore_args=Off"
          coverage: none

      - name: Install dependencies
        run: composer update

      - name: Run PHPStan
        run: ./vendor/bin/phpstan

  coding-standard:
    name: Coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          ini-values: "zend.exception_ignore_args=Off"
          coverage: none

      - name: Install dependencies
        run: composer update

      - name: Run PHP CS Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --verbose --diff

  rector:
    name: Rector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          ini-values: "zend.exception_ignore_args=Off"
          coverage: none

      - name: Install dependencies
        run: composer update

      - name: Run Rector
        run: ./vendor/bin/rector --dry-run

  check-bc:
    name: Check for BC breaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"

      - name: "Install roave/backward-compatibility-check"
        # Installing in a standalone directory to avoid any dependency conflicts / changes.
        # There is a docker action, but it appears to be outdated compared to php releases and doesn't appear to support
        # pinning to a major release.
        run: |
          mkdir bc-check
          cd bc-check
          composer require --no-interaction roave/backward-compatibility-check:^8.17

      - name: "Check for BC breaks"
        run: |
          bc-check/vendor/bin/roave-backward-compatibility-check \
            --format=github-actions

  build-phar:
    name: Build PHAR file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          ini-values: "phar.readonly=0,zend.exception_ignore_args=Off"
          coverage: none
          tools: box

      - name: Install dependencies
        run: composer update --no-dev -o

      - name: Build the PHAR
        run: box compile

      - name: cache artifact
        uses: actions/upload-artifact@v4
        with:
          name: behat.phar
          path: behat.phar

  test-phar:
    name: test PHAR file
    needs: build-phar
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          ini-values: "phar.readonly=0,zend.exception_ignore_args=Off"
          coverage: none

      - uses: actions/download-artifact@v4
        with:
          name: behat.phar

      - name: Check content
        run: ls -R .

      - name: Test the PHAR
        run: php ./behat.phar --version

  publish-phar:
    name: Publish the PHAR for release
    runs-on: ubuntu-latest
    needs: [test-phar, tests]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: behat.phar
          path: .

      - name: Upload behat.phar
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: behat.phar
          asset_name: behat.phar
          tag: ${{ github.ref }}
